spring:
  application:
    name: spring-graphql
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/field

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
